USE [master]
GO

/****** Object:  Database [dbo.Test]    Script Date: 10/5/2020 12:34:28 AM ******/
CREATE DATABASE [dbo.Test]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbo.Test', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbo.Test.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbo.Test_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbo.Test_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbo.Test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbo.Test] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbo.Test] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbo.Test] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbo.Test] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbo.Test] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbo.Test] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbo.Test] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbo.Test] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbo.Test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbo.Test] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbo.Test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbo.Test] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbo.Test] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbo.Test] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbo.Test] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbo.Test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbo.Test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbo.Test] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbo.Test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbo.Test] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbo.Test] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbo.Test] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbo.Test] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbo.Test] SET  MULTI_USER 
GO

ALTER DATABASE [dbo.Test] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbo.Test] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbo.Test] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbo.Test] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbo.Test] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbo.Test] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbo.Test] SET  READ_WRITE 
GO

